project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - slides/0a.qmd
    - slides/0b.qmd
    - slides/0c.qmd
    - slides/1a.qmd
    - slides/1b.qmd
    - slides/1c.qmd
    - slides/2a.qmd
    - slides/2b.qmd
    - slides/2c.qmd
    - materials/2a_github.qmd
    - materials/2b_devcontainers.qmd
    - materials/2c_pyproject.qmd

website:
  title: "Python Tools for Management Research"
  navbar:
    left:
      - text: "Materials"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: false
